/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LiveViewer: typeof import('./src/components/LiveViewer.vue')['default']
    WFormattedDate: typeof import('./src/components/WFormattedDate.vue')['default']
    WFormattedDay: typeof import('./src/components/WFormattedDay.vue')['default']
    WFormattedTime: typeof import('./src/components/WFormattedTime.vue')['default']
    WStateButton: typeof import('./src/components/WStateButton.vue')['default']
  }
}
