/*
 * Project: Conductor
 * Copyright (C) 2019 alf.labs gmail com,
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.alflabs.conductor.v2.ui

import org.apache.batik.css.parser.ExtendedParser
import org.apache.batik.css.parser.Parser
import org.w3c.css.sac.CSSException

import java.io.IOException

class InkscapeCssParser extends Parser {

    /**
     * Implements {@link ExtendedParser#parseStyleDeclaration(String)}.
     */
    void parseStyleDeclaration(String source) throws CSSException, IOException {
        // Batik parseStyleDeclaration throws a CSSParseException with scanner element type 5 (-)
        // being unexpected after a ; due to the "-inkscape-font-specification:'sans-serif, Normal'"
        // generated by inkscape. Simply change the element name.
        // Reference: https://stackoverflow.com/questions/42788030/batik-not-rendering-the-correct-font-color
        source = source.replaceAll(";-inkscape", ";inkscape")
        super.parseStyleDeclaration(source)
    }
}
